/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { Contract, ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import { ContractEvent, Callback, TransactionObject, BlockType } from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export class dsethtoken extends Contract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  );
  clone(): dsethtoken;
  methods: {
    name(): TransactionObject<string>;

    approve(guy: string, wad: number | string): TransactionObject<boolean>;

    totalSupply(): TransactionObject<string>;

    transferFrom(
      src: string,
      dst: string,
      wad: number | string
    ): TransactionObject<boolean>;

    withdraw(amount: number | string): TransactionObject<void>;

    decimals(): TransactionObject<string>;

    balanceOf(src: string): TransactionObject<string>;

    symbol(): TransactionObject<string>;

    transfer(dst: string, wad: number | string): TransactionObject<boolean>;

    deposit(): TransactionObject<boolean>;

    allowance(src: string, guy: string): TransactionObject<string>;

    tryWithdraw(amount: number | string): TransactionObject<boolean>;
  };
  events: {
    Deposit: ContractEvent<{
      who: string;
      amount: string;
      0: string;
      1: string;
    }>;
    Withdrawal: ContractEvent<{
      who: string;
      amount: string;
      0: string;
      1: string;
    }>;
    Transfer: ContractEvent<{
      from: string;
      to: string;
      value: string;
      0: string;
      1: string;
      2: string;
    }>;
    Approval: ContractEvent<{
      owner: string;
      spender: string;
      value: string;
      0: string;
      1: string;
      2: string;
    }>;
    allEvents: (
      options?: EventOptions,
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
}
