/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface DssProxyActionsDsr extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): DssProxyActionsDsr;
  clone(): DssProxyActionsDsr;
  methods: {
    daiJoin_join(
      apt: string,
      urn: string,
      wad: number | string
    ): NonPayableTransactionObject<void>;

    exit(
      daiJoin: string,
      pot: string,
      wad: number | string
    ): NonPayableTransactionObject<void>;

    exitAll(daiJoin: string, pot: string): NonPayableTransactionObject<void>;

    join(
      daiJoin: string,
      pot: string,
      wad: number | string
    ): NonPayableTransactionObject<void>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
