/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface LiquidityProvider extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): LiquidityProvider;
  clone(): LiquidityProvider;
  methods: {
    cancelMyOffers(
      otc: string,
      baseToken: string,
      quoteToken: string
    ): NonPayableTransactionObject<void>;

    linearOffers(
      otc: string,
      baseToken: string,
      quoteToken: string,
      midPrice: number | string,
      delta: number | string,
      baseAmount: number | string,
      count: number | string
    ): NonPayableTransactionObject<void>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
