/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type LogNote = ContractEventLog<{
  sig: string;
  usr: string;
  arg1: string;
  arg2: string;
  data: string;
  0: string;
  1: string;
  2: string;
  3: string;
  4: string;
}>;
export type Poke = ContractEventLog<{
  ilk: string;
  val: string;
  spot: string;
  0: string;
  1: string;
  2: string;
}>;

export interface McdSpot extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): McdSpot;
  clone(): McdSpot;
  methods: {
    cage(): NonPayableTransactionObject<void>;

    deny(guy: string): NonPayableTransactionObject<void>;

    "file(bytes32,bytes32,uint256)"(
      ilk: string | number[],
      what: string | number[],
      data: number | string
    ): NonPayableTransactionObject<void>;

    "file(bytes32,uint256)"(
      what: string | number[],
      data: number | string
    ): NonPayableTransactionObject<void>;

    "file(bytes32,bytes32,address)"(
      ilk: string | number[],
      what: string | number[],
      pip_: string
    ): NonPayableTransactionObject<void>;

    ilks(
      arg0: string | number[]
    ): NonPayableTransactionObject<{
      pip: string;
      mat: string;
      0: string;
      1: string;
    }>;

    live(): NonPayableTransactionObject<string>;

    par(): NonPayableTransactionObject<string>;

    poke(ilk: string | number[]): NonPayableTransactionObject<void>;

    rely(guy: string): NonPayableTransactionObject<void>;

    vat(): NonPayableTransactionObject<string>;

    wards(arg0: string): NonPayableTransactionObject<string>;
  };
  events: {
    Poke(cb?: Callback<Poke>): EventEmitter;
    Poke(options?: EventOptions, cb?: Callback<Poke>): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "Poke", cb: Callback<Poke>): void;
  once(event: "Poke", options: EventOptions, cb: Callback<Poke>): void;
}
