/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type Bite = ContractEventLog<{
  ilk: string;
  urn: string;
  ink: string;
  art: string;
  tab: string;
  flip: string;
  id: string;
  0: string;
  1: string;
  2: string;
  3: string;
  4: string;
  5: string;
  6: string;
}>;
export type LogNote = ContractEventLog<{
  sig: string;
  usr: string;
  arg1: string;
  arg2: string;
  data: string;
  0: string;
  1: string;
  2: string;
  3: string;
  4: string;
}>;

export interface McdCat extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): McdCat;
  clone(): McdCat;
  methods: {
    bite(
      ilk: string | number[],
      urn: string
    ): NonPayableTransactionObject<string>;

    box(): NonPayableTransactionObject<string>;

    cage(): NonPayableTransactionObject<void>;

    claw(rad: number | string): NonPayableTransactionObject<void>;

    deny(usr: string): NonPayableTransactionObject<void>;

    "file(bytes32,bytes32,uint256)"(
      ilk: string | number[],
      what: string | number[],
      data: number | string
    ): NonPayableTransactionObject<void>;

    "file(bytes32,uint256)"(
      what: string | number[],
      data: number | string
    ): NonPayableTransactionObject<void>;

    "file(bytes32,address)"(
      what: string | number[],
      data: string
    ): NonPayableTransactionObject<void>;

    "file(bytes32,bytes32,address)"(
      ilk: string | number[],
      what: string | number[],
      flip: string
    ): NonPayableTransactionObject<void>;

    ilks(
      arg0: string | number[]
    ): NonPayableTransactionObject<{
      flip: string;
      chop: string;
      dunk: string;
      0: string;
      1: string;
      2: string;
    }>;

    litter(): NonPayableTransactionObject<string>;

    live(): NonPayableTransactionObject<string>;

    rely(usr: string): NonPayableTransactionObject<void>;

    vat(): NonPayableTransactionObject<string>;

    vow(): NonPayableTransactionObject<string>;

    wards(arg0: string): NonPayableTransactionObject<string>;
  };
  events: {
    Bite(cb?: Callback<Bite>): EventEmitter;
    Bite(options?: EventOptions, cb?: Callback<Bite>): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "Bite", cb: Callback<Bite>): void;
  once(event: "Bite", options: EventOptions, cb: Callback<Bite>): void;
}
