/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type LogNote = ContractEventLog<{
  sig: string;
  usr: string;
  arg1: string;
  arg2: string;
  data: string;
  0: string;
  1: string;
  2: string;
  3: string;
  4: string;
}>;

export interface McdPot extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): McdPot;
  clone(): McdPot;
  methods: {
    Pie(): NonPayableTransactionObject<string>;

    cage(): NonPayableTransactionObject<void>;

    chi(): NonPayableTransactionObject<string>;

    deny(guy: string): NonPayableTransactionObject<void>;

    drip(): NonPayableTransactionObject<string>;

    dsr(): NonPayableTransactionObject<string>;

    exit(wad: number | string): NonPayableTransactionObject<void>;

    "file(bytes32,uint256)"(
      what: string | number[],
      data: number | string
    ): NonPayableTransactionObject<void>;

    "file(bytes32,address)"(
      what: string | number[],
      addr: string
    ): NonPayableTransactionObject<void>;

    join(wad: number | string): NonPayableTransactionObject<void>;

    live(): NonPayableTransactionObject<string>;

    pie(arg0: string): NonPayableTransactionObject<string>;

    rely(guy: string): NonPayableTransactionObject<void>;

    rho(): NonPayableTransactionObject<string>;

    vat(): NonPayableTransactionObject<string>;

    vow(): NonPayableTransactionObject<string>;

    wards(arg0: string): NonPayableTransactionObject<string>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
