/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type LogNote = ContractEventLog<{
  sig: string;
  usr: string;
  arg1: string;
  arg2: string;
  data: string;
  0: string;
  1: string;
  2: string;
  3: string;
  4: string;
}>;

export interface McdJug extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): McdJug;
  clone(): McdJug;
  methods: {
    base(): NonPayableTransactionObject<string>;

    deny(usr: string): NonPayableTransactionObject<void>;

    drip(ilk: string | number[]): NonPayableTransactionObject<string>;

    "file(bytes32,bytes32,uint256)"(
      ilk: string | number[],
      what: string | number[],
      data: number | string
    ): NonPayableTransactionObject<void>;

    "file(bytes32,uint256)"(
      what: string | number[],
      data: number | string
    ): NonPayableTransactionObject<void>;

    "file(bytes32,address)"(
      what: string | number[],
      data: string
    ): NonPayableTransactionObject<void>;

    ilks(
      arg0: string | number[]
    ): NonPayableTransactionObject<{
      duty: string;
      rho: string;
      0: string;
      1: string;
    }>;

    init(ilk: string | number[]): NonPayableTransactionObject<void>;

    rely(usr: string): NonPayableTransactionObject<void>;

    vat(): NonPayableTransactionObject<string>;

    vow(): NonPayableTransactionObject<string>;

    wards(arg0: string): NonPayableTransactionObject<string>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
