/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type LogNote = ContractEventLog<{
  sig: string;
  usr: string;
  arg1: string;
  arg2: string;
  data: string;
  0: string;
  1: string;
  2: string;
  3: string;
  4: string;
}>;

export interface McdJoinDai extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): McdJoinDai;
  clone(): McdJoinDai;
  methods: {
    cage(): NonPayableTransactionObject<void>;

    dai(): NonPayableTransactionObject<string>;

    deny(usr: string): NonPayableTransactionObject<void>;

    exit(usr: string, wad: number | string): NonPayableTransactionObject<void>;

    join(usr: string, wad: number | string): NonPayableTransactionObject<void>;

    live(): NonPayableTransactionObject<string>;

    rely(usr: string): NonPayableTransactionObject<void>;

    vat(): NonPayableTransactionObject<string>;

    wards(arg0: string): NonPayableTransactionObject<string>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
