/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface DsProxyFactoryInterface extends ethers.utils.Interface {
  functions: {
    "isProxy(address)": FunctionFragment;
    "cache()": FunctionFragment;
    "build()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "isProxy", values: [string]): string;
  encodeFunctionData(functionFragment: "cache", values?: undefined): string;
  encodeFunctionData(functionFragment: "build", values?: undefined): string;

  decodeFunctionResult(functionFragment: "isProxy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cache", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "build", data: BytesLike): Result;

  events: {
    "Created(address,address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Created"): EventFragment;
}

export class DsProxyFactory extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: DsProxyFactoryInterface;

  functions: {
    isProxy(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;

    "isProxy(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    cache(overrides?: CallOverrides): Promise<[string]>;

    "cache()"(overrides?: CallOverrides): Promise<[string]>;

    "build()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "build(address)"(
      owner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  isProxy(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  "isProxy(address)"(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  cache(overrides?: CallOverrides): Promise<string>;

  "cache()"(overrides?: CallOverrides): Promise<string>;

  "build()"(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "build(address)"(
    owner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    isProxy(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    "isProxy(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    cache(overrides?: CallOverrides): Promise<string>;

    "cache()"(overrides?: CallOverrides): Promise<string>;

    "build()"(overrides?: CallOverrides): Promise<string>;

    "build(address)"(owner: string, overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    Created(
      sender: string | null,
      proxy: null,
      cache: null
    ): TypedEventFilter<
      [string, string, string],
      { sender: string; proxy: string; cache: string }
    >;
  };

  estimateGas: {
    isProxy(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "isProxy(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    cache(overrides?: CallOverrides): Promise<BigNumber>;

    "cache()"(overrides?: CallOverrides): Promise<BigNumber>;

    "build()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "build(address)"(
      owner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    isProxy(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isProxy(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    cache(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "cache()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "build()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "build(address)"(
      owner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
