/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface GetCdpsInterface extends ethers.utils.Interface {
  functions: {
    "getCdpsAsc(address,address)": FunctionFragment;
    "getCdpsDesc(address,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getCdpsAsc",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getCdpsDesc",
    values: [string, string]
  ): string;

  decodeFunctionResult(functionFragment: "getCdpsAsc", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCdpsDesc",
    data: BytesLike
  ): Result;

  events: {};
}

export class GetCdps extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: GetCdpsInterface;

  functions: {
    getCdpsAsc(
      manager: string,
      guy: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber[], string[], string[]] & {
        ids: BigNumber[];
        urns: string[];
        ilks: string[];
      }
    >;

    "getCdpsAsc(address,address)"(
      manager: string,
      guy: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber[], string[], string[]] & {
        ids: BigNumber[];
        urns: string[];
        ilks: string[];
      }
    >;

    getCdpsDesc(
      manager: string,
      guy: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber[], string[], string[]] & {
        ids: BigNumber[];
        urns: string[];
        ilks: string[];
      }
    >;

    "getCdpsDesc(address,address)"(
      manager: string,
      guy: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber[], string[], string[]] & {
        ids: BigNumber[];
        urns: string[];
        ilks: string[];
      }
    >;
  };

  getCdpsAsc(
    manager: string,
    guy: string,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber[], string[], string[]] & {
      ids: BigNumber[];
      urns: string[];
      ilks: string[];
    }
  >;

  "getCdpsAsc(address,address)"(
    manager: string,
    guy: string,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber[], string[], string[]] & {
      ids: BigNumber[];
      urns: string[];
      ilks: string[];
    }
  >;

  getCdpsDesc(
    manager: string,
    guy: string,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber[], string[], string[]] & {
      ids: BigNumber[];
      urns: string[];
      ilks: string[];
    }
  >;

  "getCdpsDesc(address,address)"(
    manager: string,
    guy: string,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber[], string[], string[]] & {
      ids: BigNumber[];
      urns: string[];
      ilks: string[];
    }
  >;

  callStatic: {
    getCdpsAsc(
      manager: string,
      guy: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber[], string[], string[]] & {
        ids: BigNumber[];
        urns: string[];
        ilks: string[];
      }
    >;

    "getCdpsAsc(address,address)"(
      manager: string,
      guy: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber[], string[], string[]] & {
        ids: BigNumber[];
        urns: string[];
        ilks: string[];
      }
    >;

    getCdpsDesc(
      manager: string,
      guy: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber[], string[], string[]] & {
        ids: BigNumber[];
        urns: string[];
        ilks: string[];
      }
    >;

    "getCdpsDesc(address,address)"(
      manager: string,
      guy: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber[], string[], string[]] & {
        ids: BigNumber[];
        urns: string[];
        ilks: string[];
      }
    >;
  };

  filters: {};

  estimateGas: {
    getCdpsAsc(
      manager: string,
      guy: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getCdpsAsc(address,address)"(
      manager: string,
      guy: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getCdpsDesc(
      manager: string,
      guy: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getCdpsDesc(address,address)"(
      manager: string,
      guy: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getCdpsAsc(
      manager: string,
      guy: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getCdpsAsc(address,address)"(
      manager: string,
      guy: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCdpsDesc(
      manager: string,
      guy: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getCdpsDesc(address,address)"(
      manager: string,
      guy: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
