/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { TxManager } from "../TxManager";

export class TxManager__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): TxManager {
    return new Contract(address, _abi, signerOrProvider) as TxManager;
  }
}

const _abi = [
  {
    constant: false,
    inputs: [
      {
        name: "script",
        type: "bytes",
      },
    ],
    name: "execute",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    anonymous: true,
    inputs: [
      {
        indexed: true,
        name: "sig",
        type: "bytes4",
      },
      {
        indexed: true,
        name: "guy",
        type: "address",
      },
      {
        indexed: true,
        name: "foo",
        type: "bytes32",
      },
      {
        indexed: true,
        name: "bar",
        type: "bytes32",
      },
      {
        indexed: false,
        name: "wad",
        type: "uint256",
      },
      {
        indexed: false,
        name: "fax",
        type: "bytes",
      },
    ],
    name: "LogNote",
    type: "event",
  },
];
